### ISSUE TITLE
Errors when running

### ISSUE THREAD

**Issue by MaoYuwei** [mehmetfdemirel/microstructure#2]
Hi,

I got the Error that "PolycrystalGraph/data.py", line 68, in __getitem__
    adjacency_matrix = self.adjacency_matrix[idx].todense()
IndexError: index 1856 is out of bounds for axis 0 with size 20" when I run the model. Could you give me some advice about that? Thanks very much.

**Comment by mehmetfdemirel** [comment]
Hi! Can you elaborate as to running which script gives you this error?

**Comment by MaoYuwei** [comment]
Sorry, I found the reason now. 
I think the orders of def get_data(idx_path, running_index, folds, batch_size, max_node, num_features, num_graphs) in data.py and  get_data in model.py is different before. 
It's Ok now. 
Thanks.

**Comment by mehmetfdemirel** [comment]
Oh, that's right! Thanks for locating the bug!
